spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: "jdbc:mysql://localhost:3306/fastsns"
    username: root
    password: fast

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


